on: create
name: Deployment
jobs:
  filterTag:
    name: Filter tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Filter tag
      uses: actions/bin/filter@master
      with:
        args: tag 'v*'
    - name: Publish on PyPI
      uses: ./.github/actions/compile
      env:
        PIP_PACKAGES: twine
        PYTHON_VERSION: "3.7"
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      with:
        args: '"git submodule update --init" "pip install -e ." "rm -rf build dist"
          "python setup.py sdist" "twine upload dist/*"'
    - name: Test PyPI install
      uses: ./.github/actions/compile
      env:
        PYTHON_VERSION: "3.7"
      with:
        args: '"sleep 15" "mkdir tmp" "cd tmp" "pip install pyhector" "python -c ''import
          pyhector''"'
    - name: Create release
      uses: swillner/actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
