on: create
name: Deployment
create:
  branches:
    - master
  tags:
    - 'v*'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish on PyPI
      with:
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      run: |
        pip install twine
        git submodule update --init
        pip install -e .
        rm -rf build dist
        python setup.py sdist
        twine upload dist/*
    - name: Test PyPI release
      run: |
        sleep 15
        mkdir tmp
        cd tmp
        pip install pyhector
        python -c "import pyhector"
    - name: Create release
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Not yet supported!"
        exit 1
